[build]
    command = "npm run build"
    publish = "dist"


[context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
    command = "node server/server.js"

[context.branch-deploy]
    command = "node server/server.js"


